# ── CONFIGURATION GLOBALE ─────────────────────────────────
[agent]
  interval = "5s"          # Collecte les données toutes les 5 secondes
  flush_interval = "10s"   # Envoie les données toutes les 10 secondes
  hostname = "telegraf"    # Nom de l'agent dans les métriques

# ── INPUT : LECTURE MQTT ──────────────────────────────────
# Telegraf souscrit à Mosquitto et lit tous les messages
# publiés par le simulateur IoT sur les topics sensors/#
[[inputs.mqtt_consumer]]
  servers = ["tcp://mosquitto:1883"]  # Adresse du broker Mosquitto

  # Souscrit à tous les topics capteurs
  # Le # est un wildcard MQTT (= tous les sous-topics)
  topics = ["sensors/#"]

  # Format des messages reçus : JSON
  data_format = "json_v2"

  # Extraction des champs numériques du message JSON
  [[inputs.mqtt_consumer.json_v2]]

    # Tag = valeur textuelle pour filtrer/grouper dans Grafana
    [[inputs.mqtt_consumer.json_v2.tag]]
      path = "device_id"    # Identifiant du capteur

    [[inputs.mqtt_consumer.json_v2.tag]]
      path = "location"     # Localisation du capteur

    # Field = valeur numérique mesurée
    [[inputs.mqtt_consumer.json_v2.field]]
      path = "temperature"  # en °C

    [[inputs.mqtt_consumer.json_v2.field]]
      path = "pression"     # en hPa

    [[inputs.mqtt_consumer.json_v2.field]]
      path = "vibration"    # en g

    [[inputs.mqtt_consumer.json_v2.field]]
      path = "batterie"     # en %

# ── OUTPUT : EXPOSITION PROMETHEUS ────────────────────────
# Telegraf expose les métriques converties sur le port 9273
# Prometheus vient scraper ce port toutes les 15 secondes
[[outputs.prometheus_client]]
  listen = ":9273"          # Port d'écoute
  metric_version = 2        # Format Prometheus v2
